FROM debian:jessie
LABEL grocker.image.kind=builder grocker.version={{ version }}

ENV LANG C.UTF-8

# Copy all files to /tmp/grocker
COPY . /tmp/grocker/

# Configure apt for a lighter & quieter use.
RUN /tmp/grocker/apt-setup.sh
RUN /bin/sh /tmp/grocker/apt-repositories.sh

# Do provisioning
RUN /tmp/grocker/provision.sh
