FROM debian:jessie
LABEL grocker.image.kind=builder \
      grocker.app.runtime={{ runtime }} \
      grocker.version={{ version }}

ENV LANG=C.UTF-8 \
    GROCKER_VERSION={{ version }} \
    GROCKER_RUNTIME={{ runtime }}

# Copy all files to /tmp/grocker
COPY . /tmp/grocker/

# Configure apt for a lighter & quieter use.
RUN /tmp/grocker/apt-setup.sh
RUN /bin/sh /tmp/grocker/apt-repositories.sh

# Do provisioning
ARG SYSTEM_DEPS
RUN /tmp/grocker/provision.sh
