language: python
sudo: required
dist: xenial
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - docker

install: pip install tox-travis pytest-travis-fold
before_script: docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script: tox
