FROM {{ root_image_tag }}
LABEL grocker.image.kind=runner\
      grocker.app.name={{ app_name }} \
      grocker.app.version={{ app_version }}

ENV GROCKER_APP={{ app_name }} \
    GROCKER_APP_VERSION={{ app_version }} \
    PATH=/home/grocker/app.venv/bin/:${PATH}

# Provisioning
ARG GROCKER_PYPI_IP
COPY . /tmp/grocker
# always sync before running script to avoid "unable to execute /tmp/grocker/provision.sh: Text file busy"
RUN sync; /bin/bash /tmp/grocker/provision.sh

# Ports and Volumes
{% if ports %}EXPOSE{% for port in ports %} {{ port }}{% endfor %}{% endif %}
{% if volumes %}VOLUME {{volumes | jsonify }}{% endif %}

# Make the entry point run the compile script
USER grocker
WORKDIR /home/grocker
ENTRYPOINT ["{{ entrypoint_name }}"]
