FROM {{ root_image_tag }}
LABEL grocker.image.kind=runner

# Provisioning
COPY . /tmp/grocker
# always sync before running script to avoid "unable to execute /tmp/grocker/provision.sh: Text file busy"
RUN sync; /bin/bash /tmp/grocker/provision.sh

# Ports and Volumes
{% if ports %}EXPOSE{% for port in ports %} {{ port }}{% endfor %}{% endif %}
{% if volumes %}VOLUME {{volumes | jsonify }}{% endif %}

# Make the entry point run the compile script
USER grocker
WORKDIR /home/grocker
ENTRYPOINT ["/home/grocker/app.venv/bin/{{ entrypoint_name }}"]
