FROM {{ root_image_tag }}
LABEL grocker.image.kind=builder

COPY . /tmp/grocker

RUN /tmp/grocker/provision.sh

# Make the entry point run the compile script
USER grocker
WORKDIR /home/grocker
ENTRYPOINT ["{{ runtime }}", "/home/grocker/compile.py"]
